### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by Jaciezyt** [Jasonzyt/FakePlayerHelper#2]
- [ ] Adapt to LiteLoader 2.0
- [x] Add `extern "C"` for export APIs(Dynamic dependencies)
- [x] Add WebSocket event handler(instead of polling)
- [x] Use nlohmann/json instead of Tencent/rapidJson
- [x] {Git} Rename branch `master` to `main`
- [x] Add delete,remove_all APIs
- [x] Rewrite&Rename FPWS class
- [ ] Code format
- [x] Register plugin
- [ ] Command module
- [x] Use player real name instead of name tag
- [ ] Creat a new file for exported APIs
- [x] Use `string` to store Xuid instead of `unsigned long long`
- [x] Remove `FPHelper` namespace
- [ ] Modify FakePlayer's summoner after it connected
- [ ] Move summoner-resetting function to `onPlayerLeft`
- [ ] I18N in `Command.cpp`
- [ ] Check and create plugin folder
